intercompatible hardhat/geth deployments for compose
smartcontractkit/chainlink-node-compose pull request #8
Opened 2021-07-14 15:26 UTC by skudasov

Made geth deployment with keys and configs like in our default hardhat, so now we can run 5 nodes without ethereum client like before, and -f hh.yml or -f geth.yml with it.

2021-07-14 15:49 UTC, skudasov commented on docker-compose/.env
> +ETH_CHAIN_ID=1337
To be compatible with geth dev mode chainId must be 1337, sorry but this cannot be changed in geth https://github.com/ethereum/go-ethereum/issues/21120

2021-07-22 10:04 UTC, jleeh requested changes
Can you also put the prometheus.yml into the root of the compose folder?

2021-07-22 10:04 UTC, jleeh commented on docker-compose/ethconfig/init.sh
> +#    geth dumpconfig > /root/geth.env
Just remove any now unneeded comments

2021-07-22 10:40 UTC, jleeh approved these changes

2021-07-22 10:43 UTC, merged